# workflow name
name: CI

# workflow triggers
on:
  push:
    branches: [ master ]
    paths-ignore:
      - ".github/**"
      - "**.md"
      - ".gitignore"
      - ".editorconfig"

jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest

    steps:
      # project checkout
      - uses: actions/checkout@v2.3.4
        name: Checkout
        with:
          fetch-depth: 1000
      # jdk setup
      - uses: actions/setup-java@v1.4.3
        name: Setup JDK15
        with:
          java-version: 15
      # show env
      - name: print env
        run: |
          printenv
