# workflow name
name: CI

# workflow triggers
on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".editorconfig"

jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest

    steps:
      # setup
      - name: Prepare Environment
        run: |
          curl -o /home/runner/.local/bin/cid -L https://github.com/PhilippHeuer/cid/releases/download/latest/linux_amd64
          chmod +x /home/runner/.local/bin/cid
          cid version
      # project checkout
      - uses: actions/checkout@v2.3.4
        name: Repository Checkout
        with:
          fetch-depth: 1000
      # show env
      - name: print env
        run: |
          printenv
