# workflow name
name: CI

# workflow triggers
on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".editorconfig"

jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest

    steps:
      # setup
      - uses: cidverse/ghact-cid-setup@main
        name: CID Setup
      # project checkout
      - uses: actions/checkout@v2.3.4
        name: Repository Checkout
        with:
          fetch-depth: 1000
      # build
      - name: build
        run: |
          printenv
          cid build
