# workflow name
name: CI

# workflow triggers
on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - ".editorconfig"

jobs:
  # stages
  build:
    # runtime environment
    runs-on: ubuntu-latest

    steps:
      # setup
      - uses: cidverse/ghact-cid-setup@main
        name: CID Setup
      # project checkout
      - uses: actions/checkout@v2
        name: Repository Checkout
        with:
          fetch-depth: 0
      # print execution plan
      - name: CI Execution Plan
        run: |
          cid info
      # build
      - name: build
        run: |
          cid stage build
      - name: test
        run: |
          cid stage test
      - name: package
        run: |
          cid stage package
      - name: sast
        run: |
          cid stage sast
      - name: publish
        env:
          GPG_SIGN_KEYID: ${{ secrets.GPG_SIGN_KEYID }}
          GPG_SIGN_PRIVATEKEY: ${{ secrets.GPG_SIGN_PRIVATEKEY }}
          GPG_SIGN_PASSWORD: ${{ secrets.GPG_SIGN_PASSWORD }}
          MAVEN_REPO_URL: ${{ secrets.MAVEN_REPO_URL }}
          MAVEN_REPO_PASSWORD: ${{ secrets.MAVEN_REPO_PASSWORD }}
          MAVEN_REPO_USERNAME: ${{ secrets.MAVEN_REPO_USERNAME }}
        run: |
          echo "Maven REPO: $MAVEN_REPO_URL"
          echo "Signing KeyID: GPG_SIGN_KEYID"
          cid stage publish
